### ISSUE TITLE
Basic test case gives "Unknown frame descriptor"

### ISSUE THREAD

**Issue by pwaller** [DataDog/zstd#3] opened 2016-07-19 21:32 UTC
I just did the first thing to try this out, but it doesn't work.
# Test program

``` go
package main

import (
    "io"
    "log"
    "os"

    "github.com/DataDog/zstd"
)

func main() {
    zr := zstd.NewReader(os.Stdin)

    _, err := io.Copy(os.Stdout, zr)
    if err != nil {
        log.Fatal(err)
    }
}
```
# Error

Then I run this:

```
$ echo hello | zstd | go run program.go
```

But I get:

```
2016/07/19 21:30:35 failed to decompress: Unknown frame descriptor
```

Am I missing something obvious?

**Comment by calebdoxsey** [comment] 2016-07-20 00:25
Thanks for trying out the library.

The issue here is that this library only supports version 0.5 and below of zstd. If you were to use an older version of zstd it should work.

```
~/d/zstd † zstd --version
*** zstd command line interface 64-bits 0.5.1, by Yann Collet ***
~/d/zstd † echo hello | zstd - - | go run ~/Desktop/main.go 
hello
```

Apologies for any inconvenience, we will work on upgrading to the latest version.

**Comment by pwaller** [comment] 2016-07-20 08:46
Is there more involved in fixing it than copying in the latest zstd sources? Would it be easy for me to do this?

**Comment by calebdoxsey** [comment] 2016-07-20 14:04
I think that's probably all that needs to be happen. The API may have changed... haven't really looked to closely at it. But I believe more recent versions of the library can decompress the older versions so it's a relatively safe change.

If you want to make a go of it that would be a great help, though I'm hoping someone can take a look at this within the next couple weeks.

**Comment by pwaller** [comment] 2016-07-20 14:13
I did have a quick look this morning but I didn't have much luck and I'm not actively working on it.

**Comment by Viq111** [comment] 2016-08-10 17:07
We are definitely aiming at updating to zstd 1.0 as soon as it's out.
For intermediate versions, I was planning on updating to 0.7 but since the patches were coming out so frequently, I was waiting for the last `0.7` minor to come out (since 0.8 is on track now, `0.7.5` or `0.7.6` should be a stable one).

**Comment by iowelinux** [comment] 2016-12-08 15:47
Hi,

The issue still exists.

**Comment by prabhat003** [comment] 2016-12-21 07:48
hi caleb,
 i am facing the same issue.
But in my case I dont think that the issue is related to version. If I pipe the compressed data to the decompressStream() then the decompression is working.
```
eg. 
      var jsonData = 'some json data';
      var chunks = [];

      rs = new stream.Readable();   //created a readable stream
      rs.push(jsonData.toString());   //pushed data to the readable stream 
      rs.push(null);
      rs.pipe(compressStream());    // here compression is working
         .on('data', function(chunk){
          chunks += chunk;       //appending chunk of data to the chunks array
         })  
        .on('end', function(){
          console.log(chunks)    // Able to get the compressed data
        });
```
       For decompression I pass the chunks array as POST request body and receive this compressed            data at the server side of POST API in request stream and decompress it at the server end

```
       rstream = new stream.Readable();
       rstream.push(chunks);           // pushing compressed data in chunks array to readable stream
       rstream.push(null);
       rstream.pipe(decompreessStream())        //getting error: unknown frame descriptor
                   .pipe(process.stdout);                   //{}

```

If I try to decompress the data immediately after the compression the data gets decompressed.

```
      var jsonData = 'some json data';
      rs = new stream.Readable();   //created a readable stream
      rs.push(jsonData.toString());   //pushed data to the readable stream 
      rs.push(null);
      rs.pipe(compressStream())     // here compression is working
         .pipe(decompressStream());    //getting original data decompressed in this way  
```

**Comment by prabhat003** [comment] 2016-12-21 08:52
Any one got any idea what is going wrong. Please do reply

**Comment by Viq111** [comment] 2016-12-21 15:21
Hi,
I'm going to close this issue as we have released the binding for v1.0 (original issue) and being used for a while now.

@prabhat003 Your example seems to be for the Javascript bindings. This repo is for the Golang bindings so I'm not sure I could be of help here. I'd suggest directly trying to ask your questions to the maintainer of your library (I couldn't which one it is from your snippets but the list is available [here on the main zstd site](http://facebook.github.io/zstd/) under `Bindings for other languages`)

**Closed as completed by Viq111** 2016-12-21 15:21 UTC

**Comment by anshulchaurasia** [comment] 2019-12-16 11:19
I am getting the same issue 
Can you help me.

Compression Code:

  `     cbuf := bytes.NewBuffer(buff[:0])
	w := zstd.NewWriterLevel(cbuf, compressionLevel)
	_, err := w.Write(buf[0:])
	if err != nil {
		return nil, err
	}
	err = w.Close()

	`

I am uploading the compressed data and downloading it in a different service to decompress.

decompression code:
`func DecompressBuf(cbuf []byte) (buf []byte) {
	r:= zstd.NewReader(bytes.NewBuffer(cbuf))
	buf, err := ioutil.ReadAll(r)
	if err!=nil{
		fmt.Println(err) //decompress error: Unknown frame descriptor
	}
	return
}
`

**Comment by Viq111** [comment] 2019-12-16 22:08
Hi @anshulchaurasia 

Since you are compressing everything in one call, I'd recommend using the `Compress` / `Decompress` interface as so:

Compress:
```go
cbuf := zstd.Compress(nil, buf)
// You can upload cbuf
```

Decompress:
```go
buf := zstd.Decompress(nil, cbuf)
```

From your pasted code, it looks like you are using the same input and output buffer when using zstd. (and it's a bit hard to debug if you don't provide the compressed data (without any sensitive data))

**Comment by anshulchaurasia** [comment] 2020-01-29 07:17
Hi @Viq111 

I was not using the same input and output buffer to compress.
I started trying for small files (e.g. 50kb) and then move to the larger files so I need to keep using the same interface.
could you please explain what is the problem over here while using the different interface.


func (z *Zstd) DecompressBuf(cbuf []byte) (buf []byte, err error) {
	zr := zstd.NewReader(bytes.NewBuffer(cbuf))
	buf, err = ioutil.ReadAll(zr)
	if err != nil {
		return
	}
	return
}

**Comment by anshulchaurasia** [comment] 2020-01-29 09:54
What all would be the possible reason for this error.
It will be a great help
