### ISSUE TITLE
TestStreamCompressionDecompressionParallel frequently fails on machines with many cpus

### ISSUE THREAD

**Issue by pterjan** [DataDog/zstd#90] opened 2021-02-01 21:26 UTC
### What version of Go are you using (`go version`)?

`go version go1.15.6 linux/arm64`

### What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/iurt/.cache/go-build"
GOENV="/home/iurt/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/iurt/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/iurt/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build790893092=/tmp/go-build -gno-record-gcc-switches"

```

### What did you do?

Building golang-github-datadog-zstd 1.4.5-patch1 rpm package. It sometimes passes but most of the time fails.

```
$ go test -x
WORK=/tmp/go-build935713179
mkdir -p $WORK/b001/
mkdir -p $WORK/b019/
mkdir -p $WORK/b006/
mkdir -p $WORK/b010/
mkdir -p $WORK/b029/
mkdir -p $WORK/b013/
mkdir -p $WORK/b027/
mkdir -p $WORK/b012/
mkdir -p $WORK/b030/
mkdir -p $WORK/b011/
mkdir -p $WORK/b017/
mkdir -p $WORK/b057/
cp /home/iurt/.cache/go-build/07/071283d23ffd9eabfe3ce2a77213fdede77a69bca99ce3f55bad15bd0e82dc52-d $WORK/b057/_cgo_gotypes.go
mkdir -p $WORK/b024/
mkdir -p $WORK/b009/
cp /home/iurt/.cache/go-build/45/458a10e66e97e71eb214780d398c888757bb200bd46d52129d734e108e41ad57-d $WORK/b057/cgo.cgo1.go
cp /home/iurt/.cache/go-build/eb/ebc0b501bd5111b65729e9e43bc6238dc3804efad9dcf7b94cb214311e9b3641-d $WORK/b057/_cgo_import.go
mkdir -p $WORK/b026/
mkdir -p $WORK/b008/
mkdir -p $WORK/b005/
mkdir -p $WORK/b020/
mkdir -p $WORK/b004/
mkdir -p $WORK/b036/
mkdir -p $WORK/b014/
mkdir -p $WORK/b021/
mkdir -p $WORK/b032/
mkdir -p $WORK/b056/
mkdir -p $WORK/b028/
mkdir -p $WORK/b018/
mkdir -p $WORK/b037/
mkdir -p $WORK/b016/
mkdir -p $WORK/b025/
mkdir -p $WORK/b023/
mkdir -p $WORK/b035/
mkdir -p $WORK/b022/
mkdir -p $WORK/b042/
mkdir -p $WORK/b015/
mkdir -p $WORK/b003/
mkdir -p $WORK/b040/
mkdir -p $WORK/b039/
mkdir -p $WORK/b034/
mkdir -p $WORK/b038/
mkdir -p $WORK/b041/
mkdir -p $WORK/b033/
mkdir -p $WORK/b055/
mkdir -p $WORK/b031/
mkdir -p $WORK/b054/
cp /home/iurt/.cache/go-build/25/25252efbf11bccaafa97b69fa8ea82f65bd48a38dac9f05c8e65eb6a4d3c3d15-d $WORK/b054/_cgo_gotypes.go
cp /home/iurt/.cache/go-build/26/269217122756ca3cb5842639012f3826cf3cc6a360b6d60c8f0058ca2520158b-d $WORK/b054/errors.cgo1.go
cp /home/iurt/.cache/go-build/6c/6c6e2587e25cc71d1c138038e14ef40d0d73d668c076809c4864e93ae32fd819-d $WORK/b054/zstd.cgo1.go
cp /home/iurt/.cache/go-build/88/8812e04c91798cf5b035e0d5a583accbf4ffd0bda99fe9df31d7f24139cd7de4-d $WORK/b054/zstd_ctx.cgo1.go
cp /home/iurt/.cache/go-build/19/195c0895ff8c3d72f0a206add7f2ee648863722ddc770efd511ca51388fb332e-d $WORK/b054/zstd_stream.cgo1.go
cp /home/iurt/.cache/go-build/96/96e686d4d25f928e81ae4810ef9a14627bcb29e9ae7a6027892006311342e50b-d $WORK/b054/_cgo_import.go
cat >$WORK/b054/vet.cfg << 'EOF' # internal
{
	"ID": "_/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1",
	"Compiler": "gc",
	"Dir": "/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1",
	"ImportPath": "_/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1",
	"GoFiles": [
		"/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1/errors_test.go",
		"/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1/helpers_test.go",
		"/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1/zstd_ctx_test.go",
		"/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1/zstd_stream_test.go",
		"/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1/zstd_test.go",
		"$WORK/b054/_cgo_gotypes.go",
		"$WORK/b054/errors.cgo1.go",
		"$WORK/b054/zstd.cgo1.go",
		"$WORK/b054/zstd_ctx.cgo1.go",
		"$WORK/b054/zstd_stream.cgo1.go",
		"$WORK/b054/_cgo_import.go"
	],
	"NonGoFiles": [],
	"ImportMap": {
		"C": "C",
		"bytes": "bytes",
		"errors": "errors",
		"fmt": "fmt",
		"io": "io",
		"io/ioutil": "io/ioutil",
		"log": "log",
		"math/rand": "math/rand",
		"os": "os",
		"runtime": "runtime",
		"runtime/cgo": "runtime/cgo",
		"runtime/debug": "runtime/debug",
		"sync": "sync",
		"syscall": "syscall",
		"testing": "testing",
		"time": "time",
		"unsafe": "unsafe"
	},
	"PackageFile": {
		"bytes": "/usr/lib/golang/pkg/linux_arm64/bytes.a",
		"errors": "/usr/lib/golang/pkg/linux_arm64/errors.a",
		"fmt": "/usr/lib/golang/pkg/linux_arm64/fmt.a",
		"io": "/usr/lib/golang/pkg/linux_arm64/io.a",
		"io/ioutil": "/usr/lib/golang/pkg/linux_arm64/io/ioutil.a",
		"log": "/usr/lib/golang/pkg/linux_arm64/log.a",
		"math/rand": "/usr/lib/golang/pkg/linux_arm64/math/rand.a",
		"os": "/usr/lib/golang/pkg/linux_arm64/os.a",
		"runtime": "/usr/lib/golang/pkg/linux_arm64/runtime.a",
		"runtime/cgo": "/usr/lib/golang/pkg/linux_arm64/runtime/cgo.a",
		"runtime/debug": "/usr/lib/golang/pkg/linux_arm64/runtime/debug.a",
		"sync": "/usr/lib/golang/pkg/linux_arm64/sync.a",
		"syscall": "/usr/lib/golang/pkg/linux_arm64/syscall.a",
		"testing": "/usr/lib/golang/pkg/linux_arm64/testing.a",
		"time": "/usr/lib/golang/pkg/linux_arm64/time.a"
	},
	"Standard": {
		"bytes": true,
		"errors": true,
		"fmt": true,
		"io": true,
		"io/ioutil": true,
		"log": true,
		"math/rand": true,
		"os": true,
		"runtime": true,
		"runtime/cgo": true,
		"runtime/debug": true,
		"sync": true,
		"syscall": true,
		"testing": true,
		"time": true,
		"unsafe": true
	},
	"PackageVetx": {
		"bytes": "/home/iurt/.cache/go-build/e3/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d",
		"errors": "/home/iurt/.cache/go-build/e3/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d",
		"fmt": "/home/iurt/.cache/go-build/6f/6f1a3e1f52c31e8342fdd695153c6d7a005caa69858e5628fb700df89b134021-d",
		"io": "/home/iurt/.cache/go-build/e3/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d",
		"io/ioutil": "/home/iurt/.cache/go-build/5b/5b9172b5fe9e92464466e5c1459ae73de4a6c1cd1f7f4f795aa7a0e5ba8af6ac-d",
		"log": "/home/iurt/.cache/go-build/76/76b9459e6e6ba3a56312401978135470861b5d3081d732284d55b15b625db629-d",
		"math/rand": "/home/iurt/.cache/go-build/e3/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d",
		"os": "/home/iurt/.cache/go-build/37/376397066f40ef1fac96c02af9c4a0699a0e5aa019bc41dafa3d93954e7fe7c8-d",
		"runtime": "/home/iurt/.cache/go-build/2d/2d26f8ed83dc6de73bc9496e28d0e378ec6945d8641b2016bae22f9c0ddb929b-d",
		"runtime/cgo": "/home/iurt/.cache/go-build/e3/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d",
		"runtime/debug": "/home/iurt/.cache/go-build/7d/7d513fcf6ecfbc1b567a4f405fb6a1576ef05c49c8d868faa043913005d19976-d",
		"sync": "/home/iurt/.cache/go-build/2d/2d26f8ed83dc6de73bc9496e28d0e378ec6945d8641b2016bae22f9c0ddb929b-d",
		"syscall": "/home/iurt/.cache/go-build/77/7703a56ffad7e2d1533a584fb504cc800de76c80580922a8bc5d78959e8316c1-d",
		"testing": "/home/iurt/.cache/go-build/b4/b498e06c7950c7340d58bb00bea7e5178e197b2e50ce118ef05a726701692326-d",
		"time": "/home/iurt/.cache/go-build/77/7703a56ffad7e2d1533a584fb504cc800de76c80580922a8bc5d78959e8316c1-d"
	},
	"VetxOnly": false,
	"VetxOutput": "$WORK/b054/vet.out",
	"SucceedOnTypecheckFailure": false
}
EOF
cd /home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1
TERM='dumb' CC='/usr/bin/gcc' GCCGO='' /usr/lib/golang/pkg/tool/linux_arm64/vet -atomic -bool -buildtags -errorsas -ifaceassert -nilfunc -printf -stringintconv $WORK/b054/vet.cfg
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile _/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1.test=/home/iurt/.cache/go-build/3c/3ca69d193d6105bb30753889fdeeabd9d4730f14161e44dc46396646fca98c2a-d
packagefile os=/usr/lib/golang/pkg/linux_arm64/os.a
packagefile reflect=/usr/lib/golang/pkg/linux_arm64/reflect.a
packagefile testing=/usr/lib/golang/pkg/linux_arm64/testing.a
packagefile testing/internal/testdeps=/usr/lib/golang/pkg/linux_arm64/testing/internal/testdeps.a
packagefile runtime=/usr/lib/golang/pkg/linux_arm64/runtime.a
packagefile _/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1=/home/iurt/.cache/go-build/9c/9ce3c57ebbeb1fb2591398f8a3258b10779e0f296a0c501cd622c305e4784541-d
packagefile errors=/usr/lib/golang/pkg/linux_arm64/errors.a
packagefile internal/oserror=/usr/lib/golang/pkg/linux_arm64/internal/oserror.a
packagefile internal/poll=/usr/lib/golang/pkg/linux_arm64/internal/poll.a
packagefile internal/syscall/execenv=/usr/lib/golang/pkg/linux_arm64/internal/syscall/execenv.a
packagefile internal/syscall/unix=/usr/lib/golang/pkg/linux_arm64/internal/syscall/unix.a
packagefile internal/testlog=/usr/lib/golang/pkg/linux_arm64/internal/testlog.a
packagefile io=/usr/lib/golang/pkg/linux_arm64/io.a
packagefile sync=/usr/lib/golang/pkg/linux_arm64/sync.a
packagefile sync/atomic=/usr/lib/golang/pkg/linux_arm64/sync/atomic.a
packagefile syscall=/usr/lib/golang/pkg/linux_arm64/syscall.a
packagefile time=/usr/lib/golang/pkg/linux_arm64/time.a
packagefile internal/unsafeheader=/usr/lib/golang/pkg/linux_arm64/internal/unsafeheader.a
packagefile math=/usr/lib/golang/pkg/linux_arm64/math.a
packagefile strconv=/usr/lib/golang/pkg/linux_arm64/strconv.a
packagefile unicode=/usr/lib/golang/pkg/linux_arm64/unicode.a
packagefile unicode/utf8=/usr/lib/golang/pkg/linux_arm64/unicode/utf8.a
packagefile bytes=/usr/lib/golang/pkg/linux_arm64/bytes.a
packagefile flag=/usr/lib/golang/pkg/linux_arm64/flag.a
packagefile fmt=/usr/lib/golang/pkg/linux_arm64/fmt.a
packagefile internal/race=/usr/lib/golang/pkg/linux_arm64/internal/race.a
packagefile io/ioutil=/usr/lib/golang/pkg/linux_arm64/io/ioutil.a
packagefile runtime/debug=/usr/lib/golang/pkg/linux_arm64/runtime/debug.a
packagefile runtime/trace=/usr/lib/golang/pkg/linux_arm64/runtime/trace.a
packagefile sort=/usr/lib/golang/pkg/linux_arm64/sort.a
packagefile strings=/usr/lib/golang/pkg/linux_arm64/strings.a
packagefile bufio=/usr/lib/golang/pkg/linux_arm64/bufio.a
packagefile regexp=/usr/lib/golang/pkg/linux_arm64/regexp.a
packagefile runtime/pprof=/usr/lib/golang/pkg/linux_arm64/runtime/pprof.a
packagefile internal/bytealg=/usr/lib/golang/pkg/linux_arm64/internal/bytealg.a
packagefile internal/cpu=/usr/lib/golang/pkg/linux_arm64/internal/cpu.a
packagefile runtime/internal/atomic=/usr/lib/golang/pkg/linux_arm64/runtime/internal/atomic.a
packagefile runtime/internal/math=/usr/lib/golang/pkg/linux_arm64/runtime/internal/math.a
packagefile runtime/internal/sys=/usr/lib/golang/pkg/linux_arm64/runtime/internal/sys.a
packagefile log=/usr/lib/golang/pkg/linux_arm64/log.a
packagefile math/rand=/usr/lib/golang/pkg/linux_arm64/math/rand.a
packagefile runtime/cgo=/usr/lib/golang/pkg/linux_arm64/runtime/cgo.a
packagefile internal/reflectlite=/usr/lib/golang/pkg/linux_arm64/internal/reflectlite.a
packagefile math/bits=/usr/lib/golang/pkg/linux_arm64/math/bits.a
packagefile internal/fmtsort=/usr/lib/golang/pkg/linux_arm64/internal/fmtsort.a
packagefile path/filepath=/usr/lib/golang/pkg/linux_arm64/path/filepath.a
packagefile context=/usr/lib/golang/pkg/linux_arm64/context.a
packagefile regexp/syntax=/usr/lib/golang/pkg/linux_arm64/regexp/syntax.a
packagefile compress/gzip=/usr/lib/golang/pkg/linux_arm64/compress/gzip.a
packagefile encoding/binary=/usr/lib/golang/pkg/linux_arm64/encoding/binary.a
packagefile text/tabwriter=/usr/lib/golang/pkg/linux_arm64/text/tabwriter.a
packagefile compress/flate=/usr/lib/golang/pkg/linux_arm64/compress/flate.a
packagefile hash/crc32=/usr/lib/golang/pkg/linux_arm64/hash/crc32.a
packagefile hash=/usr/lib/golang/pkg/linux_arm64/hash.a
EOF
cd .
/usr/lib/golang/pkg/tool/linux_arm64/link -o $WORK/b001/zstd-1.4.5-patch1.test -importcfg $WORK/b001/importcfg.link -s -w -buildmode=exe -buildid=vE0vSAiEtirN37vxl8na/CtaR4_McDVI7Sxq5Z1TH/505bYDzzK5WzQ7NgBjWv/vE0vSAiEtirN37vxl8na -extld=gcc /home/iurt/.cache/go-build/3c/3ca69d193d6105bb30753889fdeeabd9d4730f14161e44dc46396646fca98c2a-d
$WORK/b001/zstd-1.4.5-patch1.test -test.timeout=10m0s
--- FAIL: TestStreamCompressionDecompressionParallel (0.00s)
    --- FAIL: TestStreamCompressionDecompressionParallel/#119 (0.01s)
        zstd_stream_test.go:115: Did not read the same �MA�.p != Hello World!
    --- FAIL: TestStreamCompressionDecompressionParallel/#159 (0.01s)
        zstd_stream_test.go:115: Did not read the same �MA�.p != Hello World!
    --- FAIL: TestStreamCompressionDecompressionParallel/#117 (0.02s)
        zstd_stream_test.go:115: Did not read the same �MA�.p != Hello World!
    --- FAIL: TestStreamCompressionDecompressionParallel/#163 (0.04s)
        zstd_stream_test.go:115: Did not read the same �MA�.p != Hello World!
FAIL
exit status 1
FAIL	_/home/iurt/rpmbuild/BUILD/zstd-1.4.5-patch1	5.307s
rm -r $WORK/b001/
```

Not sure if relevant, but the build machine has 32 cores.

**Comment by Viq111** [comment] 2021-02-02 15:24
Thanks for the report! I'll try to provision an arm64 machine this week and rerun that test.
Just to make sure, you tested without any changes on the `1.x` branch right (commit https://github.com/DataDog/zstd/commit/4b8fdbae0382a630e947bb2f528411bc37baded2 ) ?
(I'm asking because upstream [facebook/zstd](https://github.com/facebook/zstd/releases) released `1.4.7` recently that had some issues with arm64)

**Comment by pterjan** [comment] 2021-02-04 16:53
Yes this is using https://github.com/DataDog/zstd/releases/tag/v1.4.5%2Bpatch1

I made some more tests and I didn't get any failure using "taskset -a -c 0-15 go test" so the 32 cores may be a problem rather than arm64.

**Comment by pterjan** [comment] 2021-02-04 17:18
Yes, I can confirm, I could not reproduce on a 32 vcpu x86_64 VM, but could on a 64 vcpu one:

```
 go test
--- FAIL: TestStreamCompressionDecompressionParallel (0.00s)
    --- FAIL: TestStreamCompressionDecompressionParallel/#100 (0.05s)
        zstd_stream_test.go:115: Did not read the same ��C != Hello World!
FAIL
exit status 1
FAIL	_/home/pterjan/co/cauldron/golang-github-datadog-zstd/BUILD/zstd-1.4.5-patch1	2.631s
```

**Comment by Viq111** [comment] 2021-02-04 18:45
Thanks for the pointers!

I was able to reproduce on a aws `c5.9xl` (36 cores):
```
go version go1.15.7 linux/amd64
base:~/zstd (1.x✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 100
--- FAIL: TestStreamCompressionDecompressionParallel (0.00s)
    --- FAIL: TestStreamCompressionDecompressionParallel/#101 (0.01s)
        zstd_stream_test.go:115: Did not read the same �D != Hello World!
--- FAIL: TestStreamCompressionDecompressionParallel (0.00s)
    --- FAIL: TestStreamCompressionDecompressionParallel/#169 (0.02s)
        zstd_stream_test.go:115: Did not read the same 	��K�	 != Hello World!
FAIL
exit status 1
FAIL	_/home/viq111/zstd	3.005s
```

However testing previous versions:
```
base:~/zstd (1.x✘) ᐅ eval "$(~/bin/gimme 1.14)"
go version go1.14 linux/amd64
base:~/zstd (1.x✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 100
PASS
ok  	_/home/viq111/zstd	1.873s
base:~/zstd (1.x✘) ᐅ eval "$(~/bin/gimme 1.15)"
go version go1.15 linux/amd64
base:~/zstd (1.x✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 100
PASS
ok  	_/home/viq111/zstd	1.842s
base:~/zstd (1.x✘) ᐅ eval "$(~/bin/gimme 1.15.2)"
go version go1.15.2 linux/amd64
base:~/zstd (1.x✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 500
PASS
ok  	_/home/viq111/zstd	9.037s
base:~/zstd (1.x✘) ᐅ eval "$(~/bin/gimme 1.15.3)"
go version go1.15.3 linux/amd64
base:~/zstd (1.x✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 500
PASS
ok  	_/home/viq111/zstd	8.497s
base:~/zstd (1.x✘) ᐅ eval "$(~/bin/gimme 1.15.4)"
go version go1.15.4 linux/amd64
base:~/zstd (1.x✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 100
--- FAIL: TestStreamCompressionDecompressionParallel (0.00s)
    --- FAIL: TestStreamCompressionDecompressionParallel/#165 (0.00s)
        zstd_stream_test.go:115: Did not read the same �D != Hello World!
FAIL
exit status 1
FAIL	_/home/viq111/zstd	2.961s
```

Seems like it starts failing the tests with high CPU cores with `Go version >= 1.15.4`
(either a bug was introduced or the failure case happen more frequently)

I've tried updating the vendored C zsts code [here](https://github.com/DataDog/zstd/tree/viq111/zstd1.4.8):
```
base:~/zstd (1.x✘) ᐅ git checkout viq111/zstd1.4.8
Switched to branch 'viq111/zstd1.4.8'
Your branch is up-to-date with 'origin/viq111/zstd1.4.8'.
base:~/zstd (viq111/zstd1.4.8✘) ᐅ go test -run TestStreamCompressionDecompressionParallel -count 100
--- FAIL: TestStreamCompressionDecompressionParallel (0.00s)
    --- FAIL: TestStreamCompressionDecompressionParallel/#167 (0.00s)
        zstd_stream_test.go:115: Did not read the same �D != Hello World!
FAIL
exit status 1
FAIL	_/home/viq111/zstd	2.973s
```
and it still fails so something from the Go side is happening.
I'll try to dig deeper but if you have any insights into the go runtime, I'll gladly take the help

**Comment by evanj** [comment] 2021-02-05 13:35
I think I may have figured out how to reproduce this, and *maybe* how to fix it. First up: I'm going to submit a change to include a test that fails consistently, then I'll figure out if my "fix" is right ...

**Comment by evanj** [comment] 2021-02-07 17:04
Wow this was an amazing adventure. My proposed fix is in #91. If you want to read more about how this bug happens, see https://github.com/evanj/cgouintptrbug . I have wasted FAR too much time on this, but I learned a lot!

**Comment by pterjan** [comment] 2021-02-07 18:29
Thanks for the investigation, the fix and the great explanation!

**Comment by Viq111** [comment] 2021-02-16 16:46
Releases [v1.4.5+patch2](https://github.com/DataDog/zstd/releases/tag/v1.4.5%2Bpatch2) & [v1.4.8](https://github.com/DataDog/zstd/releases/tag/v1.4.8) now have this bug fixed.
Thanks for the report!

**Closed as completed by Viq111** 2021-02-16 16:46 UTC
Labels: bug, blocker
